
on: [pull_request, push]

jobs:
  add-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Get the Numbers
      run: echo "ANSWER=42" >> $GITHUB_ENV
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 27228b9af08e477a7edff3e34f829454
        filename: answer.json
        label: The Answer
        message: is ${{ env.ANSWER }}
        valColorRange: ${{ env.ANSWER }}
        maxColorRange: 100
        minColorRange: 0
